name: Python

on:
  push:
    branches: [ $default-branch ]
    paths:
      - '**/solve.py'
  pull_request:
    paths:
      - '**/solve.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.9
        with:
          files: /solve.py$

      - name: Run solution
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Run with time
        id: run-result
        run: time python ${{ steps.changed-files.outputs.all_modified_files }}
